routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/** @noinspection PhpUndefinedMethodInspection */
Auth::routes();

Route::group([
    'prefix' => '/home',
    'namespace' => 'Cabinet',
    'middleware' => ['auth', 'only_user'],
    'as' => 'home.',
], function(){
    Route::get('/', 'DefaultController@index')->name("index");

    Route::group([
        'prefix' => '/settings',
        'as' => 'settings.',
    ], function(){
        Route::get('/', 'SettingsController@index')->name('index');
        Route::post('/save', 'SettingsController@save')->name('save');
    });

    Route::group([
        'prefix' => '/robots',
        'as' => 'robots.',
    ], function(){
        Route::get('/add', 'RobotsController@add')->name('add');
        Route::post('/store', 'RobotsController@store')->name('store');
        Route::get('/{id}/edit', 'RobotsController@edit')->name('edit');
        Route::post('/{id}/change', 'RobotsController@change')->name('change');
        Route::get('/{id}/delete', 'RobotsController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/commands',
        'as' => 'commands.',
    ], function(){
        Route::get('/', 'CommandsController@index')->name('index');
        Route::get('/add', 'CommandsController@add')->name('add');
        Route::post('/store', 'CommandsController@store')->name('store');
        Route::get('/{command_id}/edit', 'CommandsController@edit')->name('edit');
        Route::post('/{command_id}/change', 'CommandsController@change')->name('change');
        Route::get('/{command_id}/delete', 'CommandsController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/movements',
        'as' => 'movements.',
    ], function(){
        Route::get('/', 'MovementsController@index')->name('index');
        Route::get('/add', 'MovementsController@add')->name('add');
        Route::post('/store', 'MovementsController@store')->name('store');
        Route::get('/{movement_id}/edit', 'MovementsController@edit')->name('edit');
        Route::post('/{movement_id}/change', 'MovementsController@change')->name('change');
        Route::get('/{movement_id}/delete', 'MovementsController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/audios',
        'as' => 'audios.',
    ], function(){
        Route::get('/', 'AudioController@index')->name('index');
        Route::get('/add', 'AudioController@add')->name('add');
        Route::post('/store', 'AudioController@store')->name('store');
        Route::get('/{id}/edit', 'AudioController@edit')->name('edit');
        Route::post('/{id}/change', 'AudioController@change')->name('change');
        Route::get('/{id}/delete', 'AudioController@delete')->name('delete');
    });
});

Route::group([
    'prefix' => '/admin',
    'namespace' => 'Admin',
    'middleware' => 'admin',
    'as' => 'admin.',
], function() {
    Route::get('/', 'DefaultController@index')->name('index');

    Route::get('/commands', 'DefaultController@commands')->name('commands');
    Route::get('/commands/add', 'DefaultController@addCommand')->name('command.add');
    Route::post('/commands/store', 'DefaultController@storeCommand')->name('command.store');
    Route::get('/commands/{id}/edit', 'DefaultController@editCommand')->name('command.edit');
    Route::post('/commands/{id}/change', 'DefaultController@changeCommand')->name('command.change');
    Route::get('/commands/{id}/delete', 'DefaultController@deleteCommand')->name('command.delete');

    Route::get('/movements', 'DefaultController@movements')->name('movements');
    Route::get('/movements/add', 'DefaultController@addMovement')->name('movement.add');
    Route::post('/movements/store', 'DefaultController@storeMovement')->name('movement.store');
    Route::get('/movements/{id}/edit', 'DefaultController@editMovement')->name('movement.edit');
    Route::post('/movements/{id}/change', 'DefaultController@changeMovement')->name('movement.change');
    Route::get('/movements/{id}/delete', 'DefaultController@deleteMovement')->name('movement.delete');

    Route::group([
        'prefix' => '/audios',
        'as' => 'audios.',
    ], function(){
        Route::get('/', 'AudioController@index')->name('index');
        Route::get('/add', 'AudioController@add')->name('add');
        Route::post('/store', 'AudioController@store')->name('store');
        Route::get('/{id}/edit', 'AudioController@edit')->name('edit');
        Route::post('/{id}/change', 'AudioController@change')->name('change');
        Route::get('/{id}/delete', 'AudioController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/missed-commands',
        'as' => 'missed_commands.',
    ], function(){
        Route::get('/', 'MissedCommandsController@index')->name('index');
        Route::get('/add', 'MissedCommandsController@add')->name('add');
        Route::post('/store', 'MissedCommandsController@store')->name('store');
        Route::get('/delete-all', 'MissedCommandsController@deleteAll')->name('delete_all');
        Route::get('/{id}/delete', 'MissedCommandsController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/updates',
        'as' => 'updates.',
    ], function(){
        Route::get('/', 'UpdatesController@index')->name('index');
        Route::get('/add', 'UpdatesController@add')->name('add');
        Route::post('/store', 'UpdatesController@store')->name('store');
        Route::get('/{id}/delete', 'UpdatesController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/users',
        'as' => 'users.',
    ], function(){
        Route::get('/', 'UsersController@index')->name('index');
        Route::get('/{id}', 'UsersController@detail')->name('detail');
        Route::get('/{id}/robots', 'UsersController@robots')->name('robots');
        Route::get('/{id}/commands', 'UsersController@commands')->name('commands');
        Route::get('/{id}/movements', 'UsersController@movements')->name('movements');
    });
});

app/Models/Movement.php
<?php

namespace App\Models;

use App\Traits\ScopeForUserTrait;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Movement
 * @package App\Models
 *
 * @property integer $id
 * @property integer $user_id
 *
 * @method static Movement forUser()
 * @method static Movement allForUser()
 * @method static Movement whereId($id)
 * @method static Movement whereUserId($user_id)
 *
 * @mixin \Eloquent
 */

class Movement extends Model
{
    use ScopeForUserTrait;

    protected $table = "movements";
    public $timestamps = false;
    protected $fillable = ['name', 'file', 'user_id'];
}

app/Http/Controllers/Api/MovementController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Movement;
use Illuminate\Database\Query\Builder;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class MovementController
{
    public function index()
    {
        $token = \Request::bearerToken();
        $user = \JWTAuth::toUser($token);

        $movements = Movement::whereIn('user_id', [0, $user->id])->get();
        return response()->json($movements, 200, [], JSON_UNESCAPED_UNICODE);
    }

    public function store(Request $request)
    {
        $token = \Request::bearerToken();
        $user = \JWTAuth::toUser($token);

        try {
            $data = $request->json()->all();

            $validator = \Validator::make($data, [
                'name' => [
                    Rule::unique('movements')->where(function (Builder $query) use ($user) {
                        return $query->where('user_id', $user->id);
                    }),
                    'required',
                ],
                'file' => 'required',
            ]);

            if (!$validator->passes()) {
                throw new \Exception($validator->errors()->first(), 500);
            }

            $content = base64_decode($data['file']);

            $dir = base_path('storage/app/public/movements/api/').$user->id;
            if (!is_dir($dir)) {
                mkdir($dir, 0777, true);
            }

            \File::put($dir."/".$data['name'].".erf", $content);
            $url = "/storage/movements/api/".$user->id."/".$data['name'].".erf";
            $movement = new Movement([
                'name' => $data['name'],
                'file' => $url,
                'user_id' => $user->id,
            ]);
            $movement->save();

            return response()->json([
                'success' => true,
                'file' => $url,
            ], 200, [], JSON_UNESCAPED_UNICODE);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage(),
            ]);
        }
    }

    public function delete($id)
    {
        $token = \Request::bearerToken();
        $user = \JWTAuth::toUser($token);

        $movement = Movement::find($id);
        if ($movement->user_id != $user->id) {
            return response()->json([
                'success' => false,
            ], 500);
        }

        Movement::destroy($id);
        return response()->json([
            'success' => true
        ]);
    }
}

app/Http/Controllers/Cabinet/AudioController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Models\Audio;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class AudioController
{
    public function index()
    {
        $custom_audios = Audio::forUser()->get();
        $audios = Audio::whereUserId(0)->get();

        return view('cabinet.audios.index', [
            'custom_audios' => $custom_audios,
            'audios' => $audios,
        ]);
    }

    public function add()
    {
        return view('cabinet.audios.add');
    }

    public function store(Request $request)
    {
        $data = $request->get('Audio');
        $file = $request->file();

        $errors = $this->validateRequest($data, $file);

        if (count($errors) == 0) {
            $movement = new Audio([
                'user_id' => \Auth::id(),
                'name' => $data['name'],
                'file' => $data['filename'],
            ]);
            $movement->save();

            return redirect()->route('home.audios.index');
        }

        return redirect()->route('home.audios.add')->withErrors($errors)->withInput($data);
    }

    public function edit($id)
    {
        $audio = $this->getAudio($id);

        return view('cabinet.audios.edit', [
            'audio' => $audio,
        ]);
    }

    public function change(Request $request, $id)
    {
        $audio = $this->getAudio($id);
        $data = $request->get('Audio');
        unset($data['filename']);
        $file = $request->file();

        $errors = $this->validateRequest($data, $file, false);

        if (count($errors) == 0) {
            $audio->fill([
                'name' => $data['name'],
            ]);

            if (isset($data['filename'])) {
                $audio->fill([
                    'file' => $data['filename'],
                ]);
            }

            $audio->save();

            return redirect()->route('home.audios.edit', [
                'id' => $id,
            ]);
        }

        return redirect()->route('home.audios.edit', [
            'id' => $id,
        ])->withErrors($errors)->withInput($data);
    }

    public function delete($id)
    {
        $audio = $this->getAudio($id);
        Audio::destroy($audio->id);
        return redirect()->route('home.audios.index');
    }

    protected function getAudio($id)
    {
        $audio = Audio::forUser()->whereId($id)->first();
        if (!$audio) {
            throw new NotFoundHttpException('Audio not found');
        }

        return $audio;
    }

    protected function validateRequest(&$data, $file, $required_file = true)
    {
        $errors = [];

        if (mb_strlen($data['name']) <= 0) {
            $errors[] = "Укажите имя";
        }

        if (count($errors) == 0 && isset($file['Audio']) && isset($file['Audio']['file'])) {
            $file = $file['Audio']['file'];
            /** @var UploadedFile $file */
            $filename = strtotime('now').mt_rand(10000, 99999).$file->getClientOriginalName();
            $link = \Storage::putFileAs('public/audios/users/'.$filename, $file, $file->getClientOriginalName());
            $data['filename'] = str_replace('public/', '/storage/', $link);
        } else {
            if ($required_file) {
                $errors[] = 'Прикрепите файл';
            }
        }

        return $errors;
    }
}

app/Http/Controllers/Cabinet/CommandsController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Http\Controllers\Controller;
use App\Models\Command;
use App\Models\Movement;
use Illuminate\Http\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class CommandsController extends Controller
{
    public function index()
    {
        $custom_commands = Command::forUser()->get();
        $commands = Command::whereUserId(0)->get();

        return view('cabinet.commands.index', [
            'custom_commands' => $custom_commands,
            'commands' => $commands,
        ]);
    }

    public function add()
    {
        $movements = Movement::allForUser()->get();

        return view('cabinet.commands.add', [
            'movements' => $movements,
        ]);
    }

    public function store(Request $request)
    {
        $data = $request->get('Command');
        $errors = $this->validateCommandRequest($data);

        if (count($errors) == 0) {
            $data['user_id'] = \Auth::id();

            $custom_command = new Command();
            $custom_command->fill($data);
            $custom_command->save();

            return redirect()->route('home.commands.index');
        }

        return redirect()->route('home.commands.add')->withErrors($errors)->withInput($data);
    }

    public function edit($id)
    {
        $command = $this->getCommand($id);
        $movements = Movement::allForUser()->get();
        return view('cabinet.commands.edit', [
            'command' => $command,
            'movements' => $movements,
        ]);
    }

    public function change(Request $request, $id)
    {
        $custom_command = $this->getCommand($id);
        $data = $request->get('Command');

        $errors = $this->validateCommandRequest($data);

        if (count($errors) == 0) {
            $custom_command->fill($data);
            $custom_command->save();
        }

        return redirect()->route('home.commands.edit', [
            'id' => $id
        ])->withErrors($errors)->withInput($data);
    }

    public function delete($id)
    {
        $command = $this->getCommand($id);
        Command::destroy($command->id);
        return redirect()->route('home.commands.index');
    }

    protected function getCommand($id)
    {
        $command = Command::forUser()->whereId($id)->first();
        if (!$command) {
            throw new NotFoundHttpException('Command not found');
        }

        return $command;
    }

    protected function validateCommandRequest($data)
    {
        $errors = [];
        if (mb_strlen($data['input']) <= 0) {
            $errors[] = 'Укажите входящую команду';
        }
        if (mb_strlen($data['output']) <= 0) {
            $errors[] = 'Укажите ответ';
        }
        if (mb_strlen($data['vocalizer']) <= 0) {
            $errors[] = 'Укажите голос';
        }

        if ($data['movement_id'] > 0) {
            $movement = Movement::allForUser()->whereId($data['movement_id'])->first();
            if (!$movement) {
                $errors[] = 'Укажите корректное движение';
            }
        }

        return $errors;
    }
}

app/Http/Controllers/Cabinet/DefaultController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Http\Controllers\Controller;
use App\Models\Robot;

class DefaultController extends Controller
{
    public function index()
    {
        $user_id = \Auth::user()->id;
        $robots = Robot::whereUserId($user_id)->get();

        return view('cabinet.index', [
            'robots' => $robots,
        ]);
    }
}

app/Http/Controllers/Cabinet/SettingsController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class SettingsController extends Controller
{
    public function index()
    {
        return view("cabinet.settings.index");
    }

    public function save(Request $request)
    {
        return redirect()->route("home.settings.index");
    }
}

resources/views/cabinet/movements/add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading lead">Добавление нового движения:</div>
                    @if (!$errors->isEmpty())
                        <div class = "error">
                            @foreach($errors->all() as $error)
                                {{$error}} <br>
                            @endforeach
                        </div>
                    @endif
                    <div class="panel-body">
                        <form class="form-horizontal" enctype="multipart/form-data" role="form" method="post" action="{{route("home.movements.store")}}">
                            {{csrf_field()}}

                            <div class="form-group">
                                <label for="movement_name" class="col-sm-2 control-label">Название команды:</label>
                                <div class="col-sm-10">
                                    <input
                                            type="text"
                                            class="form-control"
                                            id="movement_name"
                                            name="Movement[name]"
                                            placeholder="Входящая команда:"
                                            value="{{old('name')}}" >
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="movement_file" class="col-sm-2 control-label">Файл движения:</label>
                                <div class="col-sm-10">
                                    <input type="file" id="movement_file" name="Movement[file]">
                                    <p class="help-block">Файл движения формата *.erf</p>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <a href="/home/movements" class="btn btn-default">Отмена</a>
                                    <button type="submit" class="btn btn-default">Сохранить</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cabinet/movements/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading lead">Редактирование движения</div>
                    @if (!$errors->isEmpty())
                        <div class="error">
                            @foreach($errors->all() as $error)
                                {{$error}} <br>
                            @endforeach
                        </div>
                    @endif
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data"
                              action="{{route("home.movements.change", ['id' => $movement->id])}}">
                            {{csrf_field()}}

                            <div class="form-group">
                                <label for="movement_name" class="col-sm-2 control-label">Название команды:</label>
                                <div class="col-sm-10">
                                    <input
                                            type="text"
                                            class="form-control"
                                            id="movement_name"
                                            name="Movement[name]"
                                            placeholder="Входящая команда:"
                                            value="{{old('name', $movement->name)}}" >
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="movement_file" class="col-sm-2 control-label">Файл движения:</label>
                                <div class="col-sm-10">
                                    Старое движение: <a href="{{$movement->file}}">Скачать</a><br>
                                    <input type="file" id="movement_file" name="Movement[file]">
                                    <p class="help-block">Файл движения формата *.erf</p>
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <a href="/home/movements" class="btn btn-default">Отмена</a>
                                    <button type="submit" class="btn btn-default">Сохранить</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cabinet/movements/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading lead">Ваши движения</div>
                    <div class="panel-body">
                        <a class="btn btn-primary btn-sm" href ="{{route('home.movements.add')}}">Добавить Движение</a>
                        <br>
                        <br>
                        @if($custom_movements->count() > 0)
                            <table class="table">
                                <tr>
                                    <th>Имя</th>
                                    <th>Файл</th>
                                    <th>Действия</th>
                                </tr>
                                @foreach($custom_movements as $movement)
                                <tr>
                                    <td>{{$movement->name}}</td>
                                    <td>
                                        <a href="{{$movement->file}}">Скачать</a>
                                    </td>
                                    <td style="width: 200px;">
                                        <a class="btn btn-default btn-sm" href = "{{route('home.movements.edit', ['id' => $movement->id])}}">Редактировать</a>
                                        <a class="btn btn-danger btn-sm" href = "{{route('home.movements.delete', ['id' => $movement->id])}}">Удалить</a>
                                    </td>
                                </tr>
                                @endforeach
                            </table>
                        @endif
                    </div>
                    <div class="panel-heading lead">Общие движения</div>
                    <div class="panel-body">
                        @if($movements->count() > 0)
                            <table class="table">
                                <tr>
                                    <th>Имя</th>
                                    <th>Файл</th>
                                </tr>
                                @foreach($movements as $movement)
                                <tr>
                                    <td>{{$movement->name}}</td>
                                    <td>
                                        <a href="{{$movement->file}}">Скачать</a>
                                    </td>
                                </tr>
                                @endforeach
                            </table>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection