routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/** @noinspection PhpUndefinedMethodInspection */
Auth::routes();

Route::group([
    'prefix' => '/home',
    'namespace' => 'Cabinet',
    'middleware' => ['auth', 'only_user'],
    'as' => 'home.',
], function(){
    Route::get('/', 'DefaultController@index')->name("index");

    Route::group([
        'prefix' => '/settings',
        'as' => 'settings.',
    ], function(){
        Route::get('/', 'SettingsController@index')->name('index');
        Route::post('/save', 'SettingsController@save')->name('save');
    });

    Route::group([
        'prefix' => '/robots',
        'as' => 'robots.',
    ], function(){
        Route::get('/add', 'RobotsController@add')->name('add');
        Route::post('/store', 'RobotsController@store')->name('store');
        Route::get('/{id}/edit', 'RobotsController@edit')->name('edit');
        Route::post('/{id}/change', 'RobotsController@change')->name('change');
        Route::get('/{id}/delete', 'RobotsController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/commands',
        'as' => 'commands.',
    ], function(){
        Route::get('/', 'CommandsController@index')->name('index');
        Route::get('/add', 'CommandsController@add')->name('add');
        Route::post('/store', 'CommandsController@store')->name('store');
        Route::get('/{command_id}/edit', 'CommandsController@edit')->name('edit');
        Route::post('/{command_id}/change', 'CommandsController@change')->name('change');
        Route::get('/{command_id}/delete', 'CommandsController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/movements',
        'as' => 'movements.',
    ], function(){
        Route::get('/', 'MovementsController@index')->name('index');
        Route::get('/add', 'MovementsController@add')->name('add');
        Route::post('/store', 'MovementsController@store')->name('store');
        Route::get('/{movement_id}/edit', 'MovementsController@edit')->name('edit');
        Route::post('/{movement_id}/change', 'MovementsController@change')->name('change');
        Route::get('/{movement_id}/delete', 'MovementsController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/audios',
        'as' => 'audios.',
    ], function(){
        Route::get('/', 'AudioController@index')->name('index');
        Route::get('/add', 'AudioController@add')->name('add');
        Route::post('/store', 'AudioController@store')->name('store');
        Route::get('/{id}/edit', 'AudioController@edit')->name('edit');
        Route::post('/{id}/change', 'AudioController@change')->name('change');
        Route::get('/{id}/delete', 'AudioController@delete')->name('delete');
    });
});

Route::group([
    'prefix' => '/admin',
    'namespace' => 'Admin',
    'middleware' => 'admin',
    'as' => 'admin.',
], function() {
    Route::get('/', 'DefaultController@index')->name('index');

    Route::get('/commands', 'DefaultController@commands')->name('commands');
    Route::get('/commands/add', 'DefaultController@addCommand')->name('command.add');
    Route::post('/commands/store', 'DefaultController@storeCommand')->name('command.store');
    Route::get('/commands/{id}/edit', 'DefaultController@editCommand')->name('command.edit');
    Route::post('/commands/{id}/change', 'DefaultController@changeCommand')->name('command.change');
    Route::get('/commands/{id}/delete', 'DefaultController@deleteCommand')->name('command.delete');

    Route::get('/movements', 'DefaultController@movements')->name('movements');
    Route::get('/movements/add', 'DefaultController@addMovement')->name('movement.add');
    Route::post('/movements/store', 'DefaultController@storeMovement')->name('movement.store');
    Route::get('/movements/{id}/edit', 'DefaultController@editMovement')->name('movement.edit');
    Route::post('/movements/{id}/change', 'DefaultController@changeMovement')->name('movement.change');
    Route::get('/movements/{id}/delete', 'DefaultController@deleteMovement')->name('movement.delete');

    Route::group([
        'prefix' => '/audios',
        'as' => 'audios.',
    ], function(){
        Route::get('/', 'AudioController@index')->name('index');
        Route::get('/add', 'AudioController@add')->name('add');
        Route::post('/store', 'AudioController@store')->name('store');
        Route::get('/{id}/edit', 'AudioController@edit')->name('edit');
        Route::post('/{id}/change', 'AudioController@change')->name('change');
        Route::get('/{id}/delete', 'AudioController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/missed-commands',
        'as' => 'missed_commands.',
    ], function(){
        Route::get('/', 'MissedCommandsController@index')->name('index');
        Route::get('/add', 'MissedCommandsController@add')->name('add');
        Route::post('/store', 'MissedCommandsController@store')->name('store');
        Route::get('/delete-all', 'MissedCommandsController@deleteAll')->name('delete_all');
        Route::get('/{id}/delete', 'MissedCommandsController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/updates',
        'as' => 'updates.',
    ], function(){
        Route::get('/', 'UpdatesController@index')->name('index');
        Route::get('/add', 'UpdatesController@add')->name('add');
        Route::post('/store', 'UpdatesController@store')->name('store');
        Route::get('/{id}/delete', 'UpdatesController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/users',
        'as' => 'users.',
    ], function(){
        Route::get('/', 'UsersController@index')->name('index');
        Route::get('/{id}', 'UsersController@detail')->name('detail');
        Route::get('/{id}/robots', 'UsersController@robots')->name('robots');
        Route::get('/{id}/commands', 'UsersController@commands')->name('commands');
        Route::get('/{id}/movements', 'UsersController@movements')->name('movements');
    });
});

app/Http/Controllers/Admin/MissedCommandsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Command;
use App\Models\MissedCommandsLog;
use App\Models\Movement;
use Illuminate\Http\Request;

class MissedCommandsController extends Controller
{
    public function index()
    {
        $missed_commands = MissedCommandsLog::get();
        return view('admin.missed_commands.index', [
            'missed_commands' => $missed_commands,
        ]);
    }

    public function add()
    {
        $movements = Movement::whereUserId(0)->get();
        return view('admin.missed_commands.add', [
            'movements' => $movements,
        ]);
    }

    public function store(Request $request)
    {
        $data = $request->get('Command');
        $errors = $this->validateCommandRequest($data);

        if (count($errors) == 0) {
            $data['user_id'] = 0;
            $command = new Command();
            $command->fill($data);
            $command->save();

            $old_missed_commands = MissedCommandsLog::whereInput($data['input'])->get();
            foreach ($old_missed_commands as $old_missed_command) {
                MissedCommandsLog::destroy($old_missed_command->id);
            }

            return redirect()->route('admin.missed_commands.index');
        }

        return redirect()->route('admin.missed_commands.add')->withErrors($errors)->withInput($data);
    }

    protected function validateCommandRequest($data)
    {
        $errors = [];

        if (mb_strlen($data['input']) <= 0) {
            $errors[] = 'Укажите входящую команду';
        }
        if (mb_strlen($data['output']) <= 0) {
            $errors[] = 'Укажите ответ';
        }
        if (mb_strlen($data['vocalizer']) <= 0) {
            $errors[] = 'Укажите голос';
        }

        return $errors;
    }

    public function delete($id)
    {
        MissedCommandsLog::destroy($id);
        return redirect()->route('admin.missed_commands.index');
    }

    public function deleteAll()
    {
        MissedCommandsLog::truncate();
        return redirect()->route('admin.missed_commands.index');
    }
}

resources/views/admin/missed_commands/add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading lead">Добавить команду</div>
                    @if (!$errors->isEmpty())
                        <div class="error">
                            @foreach($errors->all() as $error)
                                {{$error}} <br>
                            @endforeach
                        </div>
                    @endif
                    <div class="panel-body">
                        <form method="POST" action="{{route("admin.missed_commands.store")}}" role="form"
                              class="form-horizontal">
                            {{csrf_field()}}

                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="command_input">Входящая команда:</label>
                                <div class="col-sm-10">
                                    <input id="command_input" type="text" name="Command[input]" class="form-control"
                                           value="{{old('input', \Request::get('input'))}}">
                                </div>
                            </div>

                            <div class="form-group">
                            <label class="col-sm-2 control-label" for="command_output">Ответ:</label>
                                <div class="col-sm-10">
                                    <input placeholder="Внестите ответ:" id="command_output" type="text" name="Command[output]" value="{{old('output')}}" class="form-control">
                                </div>
                            </div>

                            {{--<label for="command_vocalizer">Голос:</label>--}}
                            <input id="command_vocalizer" type="hidden" name="Command[vocalizer]" value="1">

                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="command_movement">Движение:</label>
                                <div class="col-sm-10">
                                    <select id="command_movement" name="Command[movement_id]" class="form-control">
                                        <option value=0>-</option>
                                        @foreach ($movements as $movement)
                                            @php $selected = ($movement->id == old('movement_id')) ? "selected = 'selected'" : "" @endphp
                                            <option value= {{$movement->id}} {{$selected}}>{{$movement->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <a href="/admin/missed-commands" class="btn btn-default">Отмена</a>
                                    <button class="btn btn-default" type="submit">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/missed_commands/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Диалоги без ответа</div>
                    <div class="panel-body">
                        @if ($missed_commands->count() > 0)
                        <table class="table">
                            <tr>
                                <th>Входящая команда</th>
                                <th style="width: 280px">Действия</th>
                            </tr>
                            @foreach($missed_commands as $command)
                                <tr>
                                    <td>{{$command->input}}</td>
                                    <td style="width: 280px" >
                                        <a class="btn btn-default btn-sm" href = "{{route('admin.missed_commands.add', ['input' => $command->input])}}">Добавить в общие</a>
                                        <a class="btn btn-danger btn-sm" href = "{{route('admin.missed_commands.delete', ['id' => $command->id])}}">Удалить из списка</a>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                        <br>
                        <a class="btn btn-danger btn-sm" href = "{{route('admin.missed_commands.delete_all')}}">Очистить</a>
                        @else
                            <p>Диалогов без ответа не найдено</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection