routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/** @noinspection PhpUndefinedMethodInspection */
Auth::routes();

Route::group([
    'prefix' => '/home',
    'namespace' => 'Cabinet',
    'middleware' => ['auth', 'only_user'],
    'as' => 'home.',
], function(){
    Route::get('/', 'DefaultController@index')->name("index");

    Route::group([
        'prefix' => '/settings',
        'as' => 'settings.',
    ], function(){
        Route::get('/', 'SettingsController@index')->name('index');
        Route::post('/save', 'SettingsController@save')->name('save');
    });

    Route::group([
        'prefix' => '/robots',
        'as' => 'robots.',
    ], function(){
        Route::get('/add', 'RobotsController@add')->name('add');
        Route::post('/store', 'RobotsController@store')->name('store');
        Route::get('/{id}/edit', 'RobotsController@edit')->name('edit');
        Route::post('/{id}/change', 'RobotsController@change')->name('change');
        Route::get('/{id}/delete', 'RobotsController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/commands',
        'as' => 'commands.',
    ], function(){
        Route::get('/', 'CommandsController@index')->name('index');
        Route::get('/add', 'CommandsController@add')->name('add');
        Route::post('/store', 'CommandsController@store')->name('store');
        Route::get('/{command_id}/edit', 'CommandsController@edit')->name('edit');
        Route::post('/{command_id}/change', 'CommandsController@change')->name('change');
        Route::get('/{command_id}/delete', 'CommandsController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/movements',
        'as' => 'movements.',
    ], function(){
        Route::get('/', 'MovementsController@index')->name('index');
        Route::get('/add', 'MovementsController@add')->name('add');
        Route::post('/store', 'MovementsController@store')->name('store');
        Route::get('/{movement_id}/edit', 'MovementsController@edit')->name('edit');
        Route::post('/{movement_id}/change', 'MovementsController@change')->name('change');
        Route::get('/{movement_id}/delete', 'MovementsController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/audios',
        'as' => 'audios.',
    ], function(){
        Route::get('/', 'AudioController@index')->name('index');
        Route::get('/add', 'AudioController@add')->name('add');
        Route::post('/store', 'AudioController@store')->name('store');
        Route::get('/{id}/edit', 'AudioController@edit')->name('edit');
        Route::post('/{id}/change', 'AudioController@change')->name('change');
        Route::get('/{id}/delete', 'AudioController@delete')->name('delete');
    });
});

Route::group([
    'prefix' => '/admin',
    'namespace' => 'Admin',
    'middleware' => 'admin',
    'as' => 'admin.',
], function() {
    Route::get('/', 'DefaultController@index')->name('index');

    Route::get('/commands', 'DefaultController@commands')->name('commands');
    Route::get('/commands/add', 'DefaultController@addCommand')->name('command.add');
    Route::post('/commands/store', 'DefaultController@storeCommand')->name('command.store');
    Route::get('/commands/{id}/edit', 'DefaultController@editCommand')->name('command.edit');
    Route::post('/commands/{id}/change', 'DefaultController@changeCommand')->name('command.change');
    Route::get('/commands/{id}/delete', 'DefaultController@deleteCommand')->name('command.delete');

    Route::get('/movements', 'DefaultController@movements')->name('movements');
    Route::get('/movements/add', 'DefaultController@addMovement')->name('movement.add');
    Route::post('/movements/store', 'DefaultController@storeMovement')->name('movement.store');
    Route::get('/movements/{id}/edit', 'DefaultController@editMovement')->name('movement.edit');
    Route::post('/movements/{id}/change', 'DefaultController@changeMovement')->name('movement.change');
    Route::get('/movements/{id}/delete', 'DefaultController@deleteMovement')->name('movement.delete');

    Route::group([
        'prefix' => '/audios',
        'as' => 'audios.',
    ], function(){
        Route::get('/', 'AudioController@index')->name('index');
        Route::get('/add', 'AudioController@add')->name('add');
        Route::post('/store', 'AudioController@store')->name('store');
        Route::get('/{id}/edit', 'AudioController@edit')->name('edit');
        Route::post('/{id}/change', 'AudioController@change')->name('change');
        Route::get('/{id}/delete', 'AudioController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/missed-commands',
        'as' => 'missed_commands.',
    ], function(){
        Route::get('/', 'MissedCommandsController@index')->name('index');
        Route::get('/add', 'MissedCommandsController@add')->name('add');
        Route::post('/store', 'MissedCommandsController@store')->name('store');
        Route::get('/delete-all', 'MissedCommandsController@deleteAll')->name('delete_all');
        Route::get('/{id}/delete', 'MissedCommandsController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/updates',
        'as' => 'updates.',
    ], function(){
        Route::get('/', 'UpdatesController@index')->name('index');
        Route::get('/add', 'UpdatesController@add')->name('add');
        Route::post('/store', 'UpdatesController@store')->name('store');
        Route::get('/{id}/delete', 'UpdatesController@delete')->name('delete');
    });

    Route::group([
        'prefix' => '/users',
        'as' => 'users.',
    ], function(){
        Route::get('/', 'UsersController@index')->name('index');
        Route::get('/{id}', 'UsersController@detail')->name('detail');
        Route::get('/{id}/robots', 'UsersController@robots')->name('robots');
        Route::get('/{id}/commands', 'UsersController@commands')->name('commands');
        Route::get('/{id}/movements', 'UsersController@movements')->name('movements');
    });
});

resources/views/admin/command_add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading lead">Добавить команду</div>
                    @if (!$errors->isEmpty())
                        <div class="error">
                            @foreach($errors->all() as $error)
                                {{$error}} <br>
                            @endforeach
                        </div>
                    @endif
                    <div class="panel-body">
                        <form method="POST" action="{{route("admin.command.store")}}" role="form"
                              class="form-horizontal">
                            {{csrf_field()}}

                            <div class="form-group">
                                <label for="command_input" class="col-sm-2 control-label">Входящая команда:</label>
                                <div class="col-sm-10">
                                    <input id="command_input" type="text" name="Command[input]"
                                           class="form-control"
                                           placeholder="Входящая команда:"
                                           value="{{old('input')}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="command_output" class="col-sm-2 control-label">Ответ:</label>
                                <div class="col-sm-10">
                                    <input class="form-control" placeholder="Ответ:" id="command_output" type="text" name="Command[output]" value="{{old('output')}}">
                                </div>
                            </div>

                            {{--<div class="form-group">--}}
                                {{--<label for="command_vocalizer" class="col-sm-2 control-label">Голос:</label>--}}
                                {{--<div class="col-sm-10">--}}
                                    <input id="command_vocalizer" type="hidden" name="Command[vocalizer]" class="form-control"
                                           value="{{old('vocalizer')}}">
                                {{--</div>--}}
                            {{--</div>--}}

                            <div class="form-group">
                                <label for="command_movement" class="col-sm-2 control-label">Движение:</label>
                                <div class="col-sm-10">
                                    <select id="command_movement" name="Command[movement_id]" class="form-control">
                                        <option value=0>-</option>
                                        @foreach ($movements as $movement)
                                            @php $selected = ($movement->id == old('movement_id')) ? "selected = 'selected'" : "" @endphp
                                            <option value= {{$movement->id}} {{$selected}}>{{$movement->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <a href="/admin/commands" class="btn btn-default">Отмена</a>
                                    <button type="submit" class="btn btn-default">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/command_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading lead">Команда "{{$command->input}}"</div>
                    @if (!$errors->isEmpty())
                        <div class="error">
                            @foreach($errors->all() as $error)
                                {{$error}} <br>
                            @endforeach
                        </div>
                    @endif
                    <div class="panel-body">

                        <form action="{{route("admin.command.change", ['id' => $command->id])}}" method="post"
                              role="form" class="form-horizontal">
                            {{csrf_field()}}
                            <input id="command_vocalizer" type="hidden" name="Command[vocalizer]"
                                   value="{{old('vocalizer', $command->vocalizer)}}">

                            <div class="form-group">
                                <label for="command_input" class="col-sm-2 control-label">Входящая команда:</label>
                                <div class="col-sm-10">
                                    <input
                                            type="text"
                                            class="form-control"
                                            id="command_input"
                                            name="Command[input]"
                                            placeholder="Входящая команда:"
                                            value="{{old('input', $command->input)}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="command_output" class="col-sm-2 control-label">Ответ:</label>
                                <div class="col-sm-10">
                                    <input id="command_output" type="text" name="Command[output]"
                                           class="form-control"
                                           placeholder="Ответ:"
                                           value="{{old('output', $command->output)}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="command_movement" class="col-sm-2 control-label">Движение:</label>
                                <div class="col-sm-10">
                                    <select class="form-control" id="command_movement" name="Command[movement_id]">
                                        <option value=0>-</option>
                                        @foreach ($movements as $movement)
                                            @php $selected = ($movement->id == old('movement_id', $command->movement_id)) ? "selected = 'selected'" : "" @endphp
                                            <option value= {{$movement->id}} {{$selected}}>{{$movement->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <a href="/admin/commands" class="btn btn-default">Отмена</a>
                                    <button type="submit" class="btn btn-default">Сохранить</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/commands.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Общие команды</div>
                    <div class="panel-body">
                        <a class="btn btn-primary btn-sm" href ="{{route('admin.command.add')}}">Добавить Базовый Диалог</a>
                        <br>
                        <br>
                        @if ($commands->count() > 0)
                            <table class="table">
                                <tr>
                                    <th>Входящая команда</th>
                                    <th>Ответ</th>
                                    <th>Движение</th>
                                    <th style="width: 200px;">Действия</th>
                                </tr>
                                @foreach($commands as $command)
                                <tr>
                                    <td>{{$command->input}}</td>
                                    <td>{{$command->output}}</td>
                                    <td>
                                        @if ($command->movement)
                                            {{$command->movement->name}}
                                        @endif
                                    </td>
                                    <td style="width: 200px;" >
                                        <a class="btn btn-default btn-sm" href = "{{route('admin.command.edit', ['id' => $command->id])}}">Редактировать</a>
                                        <a class="btn btn-danger btn-sm" href = "{{route('admin.command.delete', ['id' => $command->id])}}">Удалить</a>
                                    </td>
                                </tr>
                                @endforeach
                            </table>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading lead">Панель управления</div>
                    <div class="panel-body">
                        <div class="button_block">
                            <a style="width: 200px;" class="btn btn-primary btn-sm" href = "{{route('admin.commands')}}">Базовые Диалоги</a>
                            <a style="width: 200px;" class="btn btn-primary btn-sm" href = "{{route('admin.movements')}}">Базовые Движения</a>
                            <a style="width: 200px;" class="btn btn-primary btn-sm" href = "{{route('admin.missed_commands.index')}}">Список запросов без ответа</a>
                            <a style="width: 200px;" class="btn btn-primary btn-sm" href = "{{route('admin.users.index')}}">Список пользователей</a>
                            <a style="width: 200px;" class="btn btn-primary btn-sm" href = "{{route('admin.updates.index')}}">Обновления</a>
                            <a style="width: 200px;" class="btn btn-primary btn-sm" href = "{{route('admin.audios.index')}}">Аудиофайлы</a>
                        </div>

                        <p class="lead">Таблица Роботов</p>
                        <div class="table_robots">
                            <table class="table">
                                <tr>
                                    <th>IMEI Робота</th>
                                    <th>Пользователь</th>
                                    <th style="width: 150px">Действия</th>
                                </tr>
                                @foreach($robots as $robot)
                                <tr>
                                    <td>{{$robot->imei}}</td>
                                    <td>{{$robot->user->email}}</td>
                                    <td style="width: 150px">
                                        <a style="width: 150px" href="javascript:void(0);" class="btn btn-default">Информация</a>
                                    </td>
                                </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/movement_add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading lead">Добавить движение</div>
                    @if (!$errors->isEmpty())
                        <div class="error">
                            @foreach($errors->all() as $error)
                                {{$error}} <br>
                            @endforeach
                        </div>
                    @endif
                    <div class="panel-body">
                        <form method="POST" enctype="multipart/form-data" action="{{route("admin.movement.store")}}"
                              role="form" class="form-horizontal">
                            {{csrf_field()}}

                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="movement_name">Имя:</label>
                                <div class="col-sm-10">
                                    <input id="movement_name" type="text" name="Movement[name]" value="{{old('name')}}" class="form-control">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="movement_file">Движение:</label>
                                <div class="col-sm-10">
                                <input id="movement_file" type="file" name="Movement[file]" value="">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <a href="/admin/movements" class="btn btn-default">Отмена</a>
                                    <button class="btn btn-default" type="submit">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/movement_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading lead">Движение "{{$movement->name}}"</div>
                    @if (!$errors->isEmpty())
                        <div class="error">
                            @foreach($errors->all() as $error)
                                {{$error}} <br>
                            @endforeach
                        </div>
                    @endif
                    <div class="panel-body">
                        <form role="form" class="form-horizontal" method="POST" enctype="multipart/form-data"
                              action="{{route("admin.movement.change", ['movement_id' => $movement->id])}}">
                            {{csrf_field()}}

                            <div class="form-group">
                                <label for="movement_name" class="col-sm-2 control-label">Имя:</label>
                                <div class="col-sm-10">
                                <input id="movement_name" type="text" name="Movement[name]" class="form-control"
                                       value="{{old('name', $movement->name)}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="movement_file" class="control-label col-sm-2">Движение:</label>
                                <div class="col-sm-10">
                                    <input id="movement_file" type="file" name="Movement[file]" value="">
                                    Старое движение: <a href="{{$movement->file}}">Скачать</a>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <a href="/admin/movements" class="btn btn-default">Отмена</a>
                                    <button class="btn btn-default" type="submit">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/movements.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading lead">Базовые движения</div>
                    <div class="panel-body">
                        <a class="btn btn-primary btn-sm" href ="{{route('admin.movement.add')}}">Добавить базовое движение</a>
                        <br>
                        <br>
                        @if ($movements->count() > 0)
                            <table class="table">
                                <tr>
                                    <th>Имя</th>
                                    <th style="width: 200px;">Действия</th>
                                </tr>
                                @foreach($movements as $movement)
                                <tr>
                                    <td>{{$movement->name}}</td>
                                    <td style="width: 200px;">
                                        <a class="btn btn-default btn-sm" href = "{{route('admin.movement.edit', ['id' => $movement->id])}}">Редактировать</a>
                                        <a class="btn btn-danger btn-sm" href = "{{route('admin.movement.delete', ['id' => $movement->id])}}">Удалить</a>
                                    </td>
                                </tr>
                                @endforeach
                            </table>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/robots.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Роботы</div>
                    <div class="panel-body">
                        @foreach($robots as $robot)
                            {{$robot->imei}} <br>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection